// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer Vite env vars, then window.ENV fallback (public/env-config.js), then hardcoded as last resort
const env = (typeof window !== 'undefined' ? (window as any).ENV : undefined) || {};
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || env.VITE_SUPABASE_URL || "https://wepvpuuurwpbvjybdpfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlcHZwdXV1cndwYnZqeWJkcGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTQ5NTYsImV4cCI6MjA2OTAzMDk1Nn0.JfZQTwrXv46RUGmTghOf657hE0sJkVpR2aPyztzhnB0";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // eslint-disable-next-line no-console
  console.warn('Supabase URL or Anon Key is not set. Configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});